services:
  reading-tutor:
    container_name: reading-tutor
    image: reading-tutor-img
    build: ./app
    ports:
      - "5001:3000"
    environment:
      - AZURE_OPENAI_CHAT_API_KEY=${AZURE_OPENAI_CHAT_API_KEY:-}
      - AZURE_OPENAI_CHAT_ENDPOINT=${AZURE_OPENAI_CHAT_ENDPOINT:-}
      - AZURE_OPENAI_CHAT_DEPLOYMENT=${AZURE_OPENAI_CHAT_DEPLOYMENT:-}
      - AZURE_OPENAI_IMAGE_API_KEY=${AZURE_OPENAI_IMAGE_API_KEY:-}
      - AZURE_OPENAI_IMAGE_ENDPOINT=${AZURE_OPENAI_IMAGE_ENDPOINT:-}
      - AZURE_OPENAI_IMAGE_DEPLOYMENT=${AZURE_OPENAI_IMAGE_DEPLOYMENT:-}
      - IMAGE_STORAGE=/tmp/reading-tutor
    volumes:
      - ./volume:/tmp/reading-tutor
