services:
  reading-tutor-ws:
    container_name: reading-tutor-cnr
    image: reading-tutor-img
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash -c "while true; do sleep 1000; done"
    volumes:
      - ./:/workspace
    env_file:
      - ./app/.env

  reading-tutor:
    container_name: reading-tutor
    image: reading-tutor-img
    build: ./app
    ports:
      - "5001:3000"
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_CHAT_DEPLOYMENT=${AZURE_OPENAI_CHAT_DEPLOYMENT:-}
      - AZURE_OPENAI_IMAGE_DEPLOYMENT=${AZURE_OPENAI_IMAGE_DEPLOYMENT:-}
      - IMAGE_STORAGE=/tmp/reading-tutor
    volumes:
      - ./volume:/tmp/reading-tutor
