version: '3.3'

services:
  reading-tutor:
    container_name: reading-tutor
    image: reading-tutor-img
    build: .
    ports:
      - '5001:3000'
    volumes:
      - .:/app
    env_file:
      - ./.env
